
failures:

---- [ui] tests/ui/abi/stack-probes.rs#x64 stdout ----

error in revision `x64`: test run failed!
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/abi/stack-probes.x64" && RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/abi/stack-probes.x64/a"
--- stdout -------------------------------
status: signal: 11 (SIGSEGV) (core dumped)
stdout: 
stderr:
------------------------------------------
--- stderr -------------------------------
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/abi/stack-probes.rs:87:5:
assertion failed: stderr.contains("has overflowed its stack\n")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------------------------------------


---- [ui] tests/ui/associated-consts/issue-93775.rs stdout ----

error: test compilation failed although it shouldn't!
status: signal: 11 (SIGSEGV) (core dumped)
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/bin/rustc" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/associated-consts/issue-93775.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/.cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/vendor" "--sysroot" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2" "--target=x86_64-unknown-illumos" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "--out-dir" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/associated-consts/issue-93775" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/native/rust-test-helpers" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/associated-consts/issue-93775/auxiliary"
stdout: none
stderr: none


---- [ui] tests/ui/abi/stack-probes-lto.rs#x64 stdout ----

error in revision `x64`: test run failed!
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/abi/stack-probes-lto.x64" && RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/abi/stack-probes-lto.x64/a"
--- stdout -------------------------------
status: signal: 11 (SIGSEGV) (core dumped)
stdout: 
stderr:
------------------------------------------
--- stderr -------------------------------
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/abi/stack-probes.rs:87:5:
assertion failed: stderr.contains("has overflowed its stack\n")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------------------------------------


---- [ui] tests/ui/backtrace/dylib-dep.rs stdout ----

error: test run failed!
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/backtrace/dylib-dep" && RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/backtrace/dylib-dep/a"
stdout: none
--- stderr -------------------------------
-----------------------------------
looking for:
	/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/backtrace/dylib-dep.rs:69
	/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/backtrace/auxiliary/dylib-dep-helper.rs:18
	/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/backtrace/dylib-dep.rs:68
found:
Backtrace [
    { fn: "std::backtrace::Backtrace::create" },
    { fn: "std::backtrace::Backtrace::capture" },
    { fn: "std::panicking::try" },
    { fn: "std::rt::lang_start_internal" },
]
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/backtrace/dylib-dep.rs:52:9:
expected backtrace to contain /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/backtrace/dylib-dep.rs
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: std::panicking::try
  11: std::rt::lang_start_internal
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
------------------------------------------


---- [ui] tests/ui/backtrace/std-backtrace.rs stdout ----

error: test run failed!
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/backtrace/std-backtrace" && RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/backtrace/std-backtrace/a"
stdout: none
--- stderr -------------------------------
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/backtrace/std-backtrace.rs:34:5:
assertion failed: String::from_utf8_lossy(&p.stdout).contains("backtrace::main")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------------------------------------


---- [ui] tests/ui/backtrace/backtrace.rs stdout ----

error: test run failed!
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/backtrace/backtrace" && RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/backtrace/backtrace/a"
stdout: none
--- stderr -------------------------------
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/backtrace/backtrace.rs:70:5:
bad output: thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/backtrace/backtrace.rs:19:9:
explicit panic
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------------------------------------


---- [ui] tests/ui/backtrace/line-tables-only.rs stdout ----

error: test run failed!
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/backtrace/line-tables-only" && RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/backtrace/line-tables-only/a"
stdout: none
--- stderr -------------------------------
Backtrace [
    { fn: "std::panicking::try" },
    { fn: "std::rt::lang_start_internal" },
]
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/backtrace/line-tables-only.rs:32:5:
backtrace does not contain expected name foo
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: std::panicking::try
   7: std::rt::lang_start_internal
   8: <unknown>
   9: <unknown>
  10: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
------------------------------------------


---- [ui] tests/ui/closures/deeply-nested_closures.rs stdout ----

error: test compilation failed although it shouldn't!
status: signal: 11 (SIGSEGV) (core dumped)
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/bin/rustc" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/closures/deeply-nested_closures.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/.cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/vendor" "--sysroot" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2" "--target=x86_64-unknown-illumos" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "--out-dir" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/closures/deeply-nested_closures" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/native/rust-test-helpers" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/closures/deeply-nested_closures/auxiliary"
stdout: none
stderr: none


---- [ui] tests/ui/issues/issue-74564-if-expr-stack-overflow.rs stdout ----

error: test compilation failed although it shouldn't!
status: signal: 11 (SIGSEGV) (core dumped)
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/bin/rustc" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/issues/issue-74564-if-expr-stack-overflow.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/.cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/vendor" "--sysroot" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2" "--target=x86_64-unknown-illumos" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "--out-dir" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/issues/issue-74564-if-expr-stack-overflow" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/native/rust-test-helpers" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/issues/issue-74564-if-expr-stack-overflow/auxiliary"
stdout: none
stderr: none


---- [ui] tests/ui/linkage-attr/linkage-attr-does-not-panic-llvm-issue-33992.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/bin/rustc" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/linkage-attr/linkage-attr-does-not-panic-llvm-issue-33992.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/.cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/vendor" "--sysroot" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2" "--target=x86_64-unknown-illumos" "--check-cfg" "cfg(FALSE)" "-O" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "-o" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/linkage-attr/linkage-attr-does-not-panic-llvm-issue-33992/a" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/native/rust-test-helpers" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/linkage-attr/linkage-attr-does-not-panic-llvm-issue-33992/auxiliary"
stdout: none
--- stderr -------------------------------
error: linking with `gcc` failed: exit status: 1
   |
   = note: LC_ALL="C" PATH="/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/lib/rustlib/x86_64-unknown-illumos/bin:/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/lib/rustlib/x86_64-unknown-illumos/bin:/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/lib/rustlib/x86_64-unknown-illumos/bin:/opt/gcc-13/bin:/data/omnios-build/omniosorg/r151050/_extra/tools:/usr/ccs/bin:/usr/bin:/usr/sbin:/opt/ooce/bin:/usr/gnu/bin:/usr/sfw/bin" VSLANG="1033" "gcc" "-m64" "-std=c99" "/tmp/rustcQ45x7U/symbols.o" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/linkage-attr/linkage-attr-does-not-panic-llvm-issue-33992/a.linkage_attr_does_not_panic_llvm_issue_33992.d62731e8c6f2e521-cgu.0.rcgu.o" "-Wl,-z,ignore" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/native/rust-test-helpers" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/linkage-attr/linkage-attr-does-not-panic-llvm-issue-33992/auxiliary" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/lib/rustlib/x86_64-unknown-illumos/lib" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/lib/rustlib/x86_64-unknown-illumos/lib" "-Wl,-Bdynamic" "-lstd-5ac567ddc4336f41" "-Wl,-Bstatic" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/lib/rustlib/x86_64-unknown-illumos/lib/libcompiler_builtins-5f0f321d275f40bf.rlib" "-Wl,-Bdynamic" "-lsocket" "-lposix4" "-lpthread" "-lresolv" "-lnsl" "-lumem" "-lgcc_s" "-lm" "-lrt" "-lpthread" "-lsendfile" "-llgrp" "-lc" "-lssp" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/lib/rustlib/x86_64-unknown-illumos/lib" "-o" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/linkage-attr/linkage-attr-does-not-panic-llvm-issue-33992/a" "-nodefaultlibs" "-Wl,-rpath,$ORIGIN/../../../../stage2/lib/rustlib/x86_64-unknown-illumos/lib"
   = note: Undefined            first referenced
            symbol                  in file
           _ZN44linkage_attr_does_not_panic_llvm_issue_339925TEST417h4aec0b22e706e69fE /tmp/rustcQ45x7U/symbols.o
           _ZN44linkage_attr_does_not_panic_llvm_issue_339925TEST517h760d49f0d2d7d11dE /tmp/rustcQ45x7U/symbols.o
           ld: fatal: symbol referencing errors. No output written to /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/linkage-attr/linkage-attr-does-not-panic-llvm-issue-33992/a
           collect2: error: ld returned 1 exit status
           

error: aborting due to 1 previous error
------------------------------------------


---- [ui] tests/ui/panics/issue-47429-short-backtraces.rs#legacy stdout ----
diff of run.stderr:

1	thread 'main' panicked at $DIR/issue-47429-short-backtraces.rs:23:5:
2	explicit panic
3	stack backtrace:
-	   0: std::panicking::begin_panic
-	   1: issue_47429_short_backtraces::main
6	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
7	


The actual run.stderr differed from the expected run.stderr.
Actual run.stderr saved to /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/issue-47429-short-backtraces.legacy/issue-47429-short-backtraces.legacy.run.stderr

error in revision `legacy`: 1 errors occurred comparing run output.
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/issue-47429-short-backtraces.legacy" && RUST_BACKTRACE="1" RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/issue-47429-short-backtraces.legacy/a"
stdout: none
--- stderr -------------------------------
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/panics/issue-47429-short-backtraces.rs:23:5:
explicit panic
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
------------------------------------------


---- [ui] tests/ui/panics/issue-47429-short-backtraces.rs#v0 stdout ----
diff of run.stderr:

1	thread 'main' panicked at $DIR/issue-47429-short-backtraces.rs:23:5:
2	explicit panic
3	stack backtrace:
-	   0: std::panicking::begin_panic::<&str>
-	   1: issue_47429_short_backtraces::main
6	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
7	


The actual run.stderr differed from the expected run.stderr.
Actual run.stderr saved to /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/issue-47429-short-backtraces.v0/issue-47429-short-backtraces.v0.run.stderr

error in revision `v0`: 1 errors occurred comparing run output.
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/issue-47429-short-backtraces.v0" && RUST_BACKTRACE="1" RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/issue-47429-short-backtraces.v0/a"
stdout: none
--- stderr -------------------------------
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/panics/issue-47429-short-backtraces.rs:23:5:
explicit panic
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
------------------------------------------


---- [ui] tests/ui/panics/default-backtrace-ice.rs stdout ----
diff of stderr:

8	aborting due to `-Z treat-err-as-bug=1`
9	stack backtrace:
10	(end_short_backtrace)
-	(begin_short_backtrace)
-	(end_short_backtrace)
-	(begin_short_backtrace)
14	
15	error: the compiler unexpectedly panicked. this is a bug.
16	


The actual stderr differed from the expected stderr.
Actual stderr saved to /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/default-backtrace-ice/default-backtrace-ice.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args panics/default-backtrace-ice.rs`

error: 1 errors occurred comparing output.
status: exit status: 101
command: env -u RUSTC_LOG_COLOR -u RUST_BACKTRACE RUSTC_ICE="0" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/bin/rustc" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/panics/default-backtrace-ice.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/.cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/vendor" "--sysroot" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2" "--target=x86_64-unknown-illumos" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/default-backtrace-ice" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/native/rust-test-helpers" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/default-backtrace-ice/auxiliary" "-Z" "treat-err-as-bug=1"
stdout: none
--- stderr -------------------------------
error: internal compiler error[E0425]: cannot find value `missing_ident` in this scope
  --> /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/panics/default-backtrace-ice.rs:21:13
   |
LL | fn main() { missing_ident; }
   |             ^^^^^^^^^^^^^ not found in this scope

thread 'rustc' panicked at compiler/rustc_errors/src/lib.rs:1745:17:
aborting due to `-Z treat-err-as-bug=1`
stack backtrace:
   0: 0xfffffaffe6bb8e7f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc081a55a0f1780b5
   1: 0xfffffaffe6c2e49b - core::fmt::write::h35f0fe8e729713e4
   2: 0xfffffaffe6bf6a18 - std::io::Write::write_fmt::heb110bcb762ba542
   3: 0xfffffaffe6bb8c77 - std::sys_common::backtrace::print::h0c24713efa5b4e4b
   4: 0xfffffaffe6bc0f5a - std::panicking::default_hook::{{closure}}::hf5143a727765c9bd
   5: 0xfffffaffe6bc0c52 - std::panicking::default_hook::hf518dfe583c971c6
   6: 0xfffffaffd804a27c - <unknown>
   7: 0xfffffaffe6bc1821 - std::panicking::rust_panic_with_hook::h6f0cad0c94a63f1a
   8: 0xfffffaffe6bb945a - std::panicking::begin_panic_handler::{{closure}}::h7c1e1664d69f4de8
   9: 0xfffffaffe6bb9089 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ece08c990f68b6e
  10: 0xfffffaffe6bc13b6 - rust_begin_unwind
  11: 0xfffffaffe6c3afb2 - core::panicking::panic_fmt::h7b1aecc2da5994b5
  12: 0xfffffaffde69e0f8 - <unknown>
  13: 0xfffffaffde69d542 - <unknown>
  14: 0xfffffaffd8239c17 - <unknown>
  15: 0xfffffaffde69cb6c - <unknown>
  16: 0xfffffaffde6ef7e3 - <unknown>
  17: 0xfffffaffdcbbdd84 - <unknown>
  18: 0xfffffaffdcc70f0b - <unknown>
  19: 0xfffffaffdcbf2f5e - <unknown>
  20: 0xfffffaffd8265b72 - <unknown>
  21: 0xfffffaffdcfa7602 - <unknown>
  22: 0xfffffaffdd0755ad - <unknown>
  23: 0xfffffaffdd239208 - <unknown>
  24: 0xfffffaffdd15cff2 - <unknown>
  25: 0xfffffaffdea860b6 - <unknown>
  26: 0xfffffaffdea86949 - <unknown>
  27: 0xfffffaffdea8667e - <unknown>
  28: 0xfffffaffdd170d0d - <unknown>
  29: 0xfffffaffde32b244 - <unknown>
  30: 0xfffffaffd8026484 - <unknown>
  31: 0xfffffaffd7fe2957 - <unknown>
  32: 0xfffffaffd8011e2a - <unknown>
  33: 0xfffffaffd7fe2221 - <unknown>
  34: 0xfffffaffd8048295 - <unknown>
  35: 0xfffffaffd801e132 - <unknown>
  36: 0xfffffaffe6bc727b - std::sys::pal::unix::thread::Thread::new::thread_start::hb33981c781d77ec2
  37: 0xfffffaffe8a33e67 - _thrp_setup
  38: 0xfffffaffe8a341b0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.80.1 (3f5fd8dd4 2024-08-06) (OmniOS/151050) running on x86_64-unknown-illumos

note: compiler flags: -Z threads=1 -Z simulate-remapped-rust-src-base=/rustc/FAKE_PREFIX -Z translate-remapped-path-to-local-path=no -Z ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/.cargo -Z ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/vendor -C codegen-units=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z write-long-types-to-disk=no -C strip=debuginfo -C prefer-dynamic -C rpath -C debuginfo=0 -Z treat-err-as-bug=1

query stack during panic:
#0 [resolver_for_lowering_raw] getting the resolver for lowering
end of query stack
------------------------------------------


---- [ui] tests/ui/panics/short-ice-remove-middle-frames.rs stdout ----
diff of run.stderr:

1	thread 'main' panicked at $DIR/short-ice-remove-middle-frames.rs:52:5:
2	debug!!!
3	stack backtrace:
-	   0: std::panicking::begin_panic
-	   1: short_ice_remove_middle_frames::seven
-	   2: short_ice_remove_middle_frames::sixth
-	   3: short_ice_remove_middle_frames::fifth::{{closure}}
-	      [... omitted 4 frames ...]
-	   4: short_ice_remove_middle_frames::second
-	   5: short_ice_remove_middle_frames::first::{{closure}}
-	   6: short_ice_remove_middle_frames::first
-	   7: short_ice_remove_middle_frames::main
-	   8: core::ops::function::FnOnce::call_once
14	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
15	


The actual run.stderr differed from the expected run.stderr.
Actual run.stderr saved to /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/short-ice-remove-middle-frames/short-ice-remove-middle-frames.run.stderr

error: 1 errors occurred comparing run output.
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/short-ice-remove-middle-frames" && RUST_BACKTRACE="1" RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/short-ice-remove-middle-frames/a"
stdout: none
--- stderr -------------------------------
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/panics/short-ice-remove-middle-frames.rs:52:5:
debug!!!
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
------------------------------------------


---- [ui] tests/ui/panics/runtime-switch.rs#v0 stdout ----
diff of run.stderr:

1	thread 'main' panicked at $DIR/runtime-switch.rs:26:5:
2	explicit panic
3	stack backtrace:
-	   0: std::panicking::begin_panic::<&str>
-	   1: runtime_switch::main
6	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
7	


The actual run.stderr differed from the expected run.stderr.
Actual run.stderr saved to /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/runtime-switch.v0/runtime-switch.v0.run.stderr

error in revision `v0`: 1 errors occurred comparing run output.
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/runtime-switch.v0" && RUST_BACKTRACE="0" RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/runtime-switch.v0/a"
stdout: none
--- stderr -------------------------------
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/panics/runtime-switch.rs:26:5:
explicit panic
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
------------------------------------------


---- [ui] tests/ui/panics/runtime-switch.rs#legacy stdout ----
diff of run.stderr:

1	thread 'main' panicked at $DIR/runtime-switch.rs:26:5:
2	explicit panic
3	stack backtrace:
-	   0: std::panicking::begin_panic
-	   1: runtime_switch::main
6	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
7	


The actual run.stderr differed from the expected run.stderr.
Actual run.stderr saved to /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/runtime-switch.legacy/runtime-switch.legacy.run.stderr

error in revision `legacy`: 1 errors occurred comparing run output.
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/runtime-switch.legacy" && RUST_BACKTRACE="0" RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/runtime-switch.legacy/a"
stdout: none
--- stderr -------------------------------
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/panics/runtime-switch.rs:26:5:
explicit panic
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
------------------------------------------


---- [ui] tests/ui/panics/short-ice-remove-middle-frames-2.rs stdout ----
diff of run.stderr:

1	thread 'main' panicked at $DIR/short-ice-remove-middle-frames-2.rs:56:5:
2	debug!!!
3	stack backtrace:
-	   0: std::panicking::begin_panic
-	   1: short_ice_remove_middle_frames_2::eight
-	   2: short_ice_remove_middle_frames_2::seven::{{closure}}
-	      [... omitted 3 frames ...]
-	   3: short_ice_remove_middle_frames_2::fifth
-	   4: short_ice_remove_middle_frames_2::fourth::{{closure}}
-	      [... omitted 4 frames ...]
-	   5: short_ice_remove_middle_frames_2::first
-	   6: short_ice_remove_middle_frames_2::main
-	   7: core::ops::function::FnOnce::call_once
14	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
15	


The actual run.stderr differed from the expected run.stderr.
Actual run.stderr saved to /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/short-ice-remove-middle-frames-2/short-ice-remove-middle-frames-2.run.stderr

error: 1 errors occurred comparing run output.
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/short-ice-remove-middle-frames-2" && RUST_BACKTRACE="1" RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/panics/short-ice-remove-middle-frames-2/a"
stdout: none
--- stderr -------------------------------
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/panics/short-ice-remove-middle-frames-2.rs:56:5:
debug!!!
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
------------------------------------------


---- [ui] tests/ui/parser/survive-peano-lesson-queue.rs stdout ----

error: test compilation failed although it shouldn't!
status: signal: 11 (SIGSEGV) (core dumped)
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/bin/rustc" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/parser/survive-peano-lesson-queue.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/.cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/vendor" "--sysroot" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2" "--target=x86_64-unknown-illumos" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "--out-dir" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/parser/survive-peano-lesson-queue" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/native/rust-test-helpers" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/parser/survive-peano-lesson-queue/auxiliary"
stdout: none
stderr: none


---- [ui] tests/ui/proc-macro/load-panic-backtrace.rs stdout ----
diff of stderr:

1	at $DIR/auxiliary/test-macros.rs:43:5:
2	panic-derive
+	
+	error: the compiler unexpectedly panicked. this is a bug.
+	
+	note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
+	
+	note: please make sure that you have updated to the latest nightly
+	
+	note: rustc 1.80.1 (3f5fd8dd4 2024-08-06) (OmniOS/151050) running on x86_64-unknown-illumos
+	
+	note: compiler flags: -Z threads=1 -Z simulate-remapped-rust-src-base=/rustc/FAKE_PREFIX -Z translate-remapped-path-to-local-path=no -Z ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/.cargo -Z ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/vendor -C codegen-units=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z write-long-types-to-disk=no -C strip=debuginfo -C prefer-dynamic -C rpath -C debuginfo=0 -Z proc-macro-backtrace
+	
+	query stack during panic:
+	#0 [resolver_for_lowering_raw] getting the resolver for lowering
+	end of query stack
3	error: proc-macro derive panicked
4	  --> $DIR/load-panic-backtrace.rs:11:10
5	   |


The actual stderr differed from the expected stderr.
Actual stderr saved to /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/proc-macro/load-panic-backtrace/load-panic-backtrace.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args proc-macro/load-panic-backtrace.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="0" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/bin/rustc" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/proc-macro/load-panic-backtrace.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/.cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/vendor" "--sysroot" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2" "--target=x86_64-unknown-illumos" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/proc-macro/load-panic-backtrace" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/native/rust-test-helpers" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/proc-macro/load-panic-backtrace/auxiliary" "-Z" "proc-macro-backtrace"
stdout: none
--- stderr -------------------------------
thread 'rustc' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/proc-macro/auxiliary/test-macros.rs:43:5:
panic-derive
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.80.1 (3f5fd8dd4 2024-08-06) (OmniOS/151050) running on x86_64-unknown-illumos

note: compiler flags: -Z threads=1 -Z simulate-remapped-rust-src-base=/rustc/FAKE_PREFIX -Z translate-remapped-path-to-local-path=no -Z ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/.cargo -Z ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/vendor -C codegen-units=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z write-long-types-to-disk=no -C strip=debuginfo -C prefer-dynamic -C rpath -C debuginfo=0 -Z proc-macro-backtrace

query stack during panic:
#0 [resolver_for_lowering_raw] getting the resolver for lowering
end of query stack
error: proc-macro derive panicked
  --> /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/proc-macro/load-panic-backtrace.rs:11:10
   |
LL | #[derive(Panic)]
   |          ^^^^^
   |
   = help: message: panic-derive

error: aborting due to 1 previous error
------------------------------------------


---- [ui] tests/ui/runtime/backtrace-debuginfo.rs stdout ----

error: test run failed!
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/runtime/backtrace-debuginfo" && RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/runtime/backtrace-debuginfo/a"
--- stdout -------------------------------
---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:184", "backtrace-debuginfo.rs:120"]

--- stdout
backtrace-debuginfo.rs:120
backtrace-debuginfo.rs:184

--- stderr
test case 0
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/runtime/backtrace-debuginfo.rs:81:5:
explicit panic
stack backtrace:
   0: 0xfffffaffeed68e7f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc081a55a0f1780b5
   1: 0xfffffaffeedde49b - core::fmt::write::h35f0fe8e729713e4
   2: 0xfffffaffeeda6a18 - std::io::Write::write_fmt::heb110bcb762ba542
   3: 0xfffffaffeed68c77 - std::sys_common::backtrace::print::h0c24713efa5b4e4b
   4: 0xfffffaffeed70f5a - std::panicking::default_hook::{{closure}}::hf5143a727765c9bd
   5: 0xfffffaffeed70c52 - std::panicking::default_hook::hf518dfe583c971c6
   6: 0xfffffaffeed71802 - std::panicking::rust_panic_with_hook::h6f0cad0c94a63f1a
   7:           0x418bff - <unknown>
   8:           0x41791d - <unknown>
   9:           0x418ba1 - <unknown>
  10:           0x428507 - <unknown>
  11:           0x428c35 - <unknown>
  12:           0x42a1ee - <unknown>
  13:           0x419d9e - <unknown>
  14:           0x417931 - <unknown>
  15:           0x4187b4 - <unknown>
  16: 0xfffffaffeed71214 - std::panicking::try::h44b63116cd2b01fa
  17: 0xfffffaffeeda0d3c - std::rt::lang_start_internal::h3c4b2151dc4654ff
  18:           0x418787 - <unknown>
  19:           0x42a251 - <unknown>
  20:           0x415eb7 - <unknown>
  21:           0x415e18 - <unknown>

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:184", "backtrace-debuginfo.rs:120"]

--- stdout
backtrace-debuginfo.rs:120
backtrace-debuginfo.rs:184

--- stderr
test case 1
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/runtime/backtrace-debuginfo.rs:82:5:
explicit panic
stack backtrace:
   0: 0xfffffaffeed18e7f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc081a55a0f1780b5
   1: 0xfffffaffeed8e49b - core::fmt::write::h35f0fe8e729713e4
   2: 0xfffffaffeed56a18 - std::io::Write::write_fmt::heb110bcb762ba542
   3: 0xfffffaffeed18c77 - std::sys_common::backtrace::print::h0c24713efa5b4e4b
   4: 0xfffffaffeed20f5a - std::panicking::default_hook::{{closure}}::hf5143a727765c9bd
   5: 0xfffffaffeed20c52 - std::panicking::default_hook::hf518dfe583c971c6
   6: 0xfffffaffeed21802 - std::panicking::rust_panic_with_hook::h6f0cad0c94a63f1a
   7:           0x418bff - <unknown>
   8:           0x41791d - <unknown>
   9:           0x418ba1 - <unknown>
  10:           0x4285ab - <unknown>
  11:           0x428c35 - <unknown>
  12:           0x42a1ee - <unknown>
  13:           0x419d9e - <unknown>
  14:           0x417931 - <unknown>
  15:           0x4187b4 - <unknown>
  16: 0xfffffaffeed21214 - std::panicking::try::h44b63116cd2b01fa
  17: 0xfffffaffeed50d3c - std::rt::lang_start_internal::h3c4b2151dc4654ff
  18:           0x418787 - <unknown>
  19:           0x42a251 - <unknown>
  20:           0x415eb7 - <unknown>
  21:           0x415e18 - <unknown>

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:184", "backtrace-debuginfo.rs:120", "backtrace-debuginfo.rs:83", "backtrace-debuginfo-aux.rs:6"]

--- stdout
backtrace-debuginfo-aux.rs:6
backtrace-debuginfo.rs:83
backtrace-debuginfo.rs:120
backtrace-debuginfo.rs:184

--- stderr
test case 2
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/runtime/backtrace-debuginfo.rs:84:9:
explicit panic
stack backtrace:
   0: 0xfffffaffef148e7f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc081a55a0f1780b5
   1: 0xfffffaffef1be49b - core::fmt::write::h35f0fe8e729713e4
   2: 0xfffffaffef186a18 - std::io::Write::write_fmt::heb110bcb762ba542
   3: 0xfffffaffef148c77 - std::sys_common::backtrace::print::h0c24713efa5b4e4b
   4: 0xfffffaffef150f5a - std::panicking::default_hook::{{closure}}::hf5143a727765c9bd
   5: 0xfffffaffef150c52 - std::panicking::default_hook::hf518dfe583c971c6
   6: 0xfffffaffef151802 - std::panicking::rust_panic_with_hook::h6f0cad0c94a63f1a
   7:           0x418bff - <unknown>
   8:           0x41791d - <unknown>
   9:           0x418ba1 - <unknown>
  10:           0x4287cb - <unknown>
  11:           0x428233 - <unknown>
  12:           0x428626 - <unknown>
  13:           0x428c35 - <unknown>
  14:           0x42a1ee - <unknown>
  15:           0x419d9e - <unknown>
  16:           0x417931 - <unknown>
  17:           0x4187b4 - <unknown>
  18: 0xfffffaffef151214 - std::panicking::try::h44b63116cd2b01fa
  19: 0xfffffaffef180d3c - std::rt::lang_start_internal::h3c4b2151dc4654ff
  20:           0x418787 - <unknown>
  21:           0x42a251 - <unknown>
  22:           0x415eb7 - <unknown>
  23:           0x415e18 - <unknown>

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:184", "backtrace-debuginfo.rs:120", "backtrace-debuginfo.rs:86", "backtrace-debuginfo-aux.rs:13"]

--- stdout
backtrace-debuginfo-aux.rs:13
backtrace-debuginfo.rs:86
backtrace-debuginfo.rs:120
backtrace-debuginfo.rs:184

--- stderr
test case 3
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/runtime/backtrace-debuginfo.rs:87:9:
explicit panic
stack backtrace:
   0: 0xfffffaffef0e8e7f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc081a55a0f1780b5
   1: 0xfffffaffef15e49b - core::fmt::write::h35f0fe8e729713e4
   2: 0xfffffaffef126a18 - std::io::Write::write_fmt::heb110bcb762ba542
   3: 0xfffffaffef0e8c77 - std::sys_common::backtrace::print::h0c24713efa5b4e4b
   4: 0xfffffaffef0f0f5a - std::panicking::default_hook::{{closure}}::hf5143a727765c9bd
   5: 0xfffffaffef0f0c52 - std::panicking::default_hook::hf518dfe583c971c6
   6: 0xfffffaffef0f1802 - std::panicking::rust_panic_with_hook::h6f0cad0c94a63f1a
   7:           0x418bff - <unknown>
   8:           0x41791d - <unknown>
   9:           0x418ba1 - <unknown>
  10:           0x42890b - <unknown>
  11:           0x4286a8 - <unknown>
  12:           0x428c35 - <unknown>
  13:           0x42a1ee - <unknown>
  14:           0x419d9e - <unknown>
  15:           0x417931 - <unknown>
  16:           0x4187b4 - <unknown>
  17: 0xfffffaffef0f1214 - std::panicking::try::h44b63116cd2b01fa
  18: 0xfffffaffef120d3c - std::rt::lang_start_internal::h3c4b2151dc4654ff
  19:           0x418787 - <unknown>
  20:           0x42a251 - <unknown>
  21:           0x415eb7 - <unknown>
  22:           0x415e18 - <unknown>

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:184", "backtrace-debuginfo.rs:121"]

--- stdout
backtrace-debuginfo.rs:121
backtrace-debuginfo.rs:184

--- stderr
test case 4
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/runtime/backtrace-debuginfo.rs:95:5:
explicit panic
stack backtrace:
   0: 0xfffffaffef1b8e7f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc081a55a0f1780b5
   1: 0xfffffaffef22e49b - core::fmt::write::h35f0fe8e729713e4
   2: 0xfffffaffef1f6a18 - std::io::Write::write_fmt::heb110bcb762ba542
   3: 0xfffffaffef1b8c77 - std::sys_common::backtrace::print::h0c24713efa5b4e4b
   4: 0xfffffaffef1c0f5a - std::panicking::default_hook::{{closure}}::hf5143a727765c9bd
   5: 0xfffffaffef1c0c52 - std::panicking::default_hook::hf518dfe583c971c6
   6: 0xfffffaffef1c1802 - std::panicking::rust_panic_with_hook::h6f0cad0c94a63f1a
   7:           0x418bff - <unknown>
   8:           0x41791d - <unknown>
   9:           0x418ba1 - <unknown>
  10:           0x428cfa - <unknown>
  11:           0x42a1ee - <unknown>
  12:           0x419d9e - <unknown>
  13:           0x417931 - <unknown>
  14:           0x4187b4 - <unknown>
  15: 0xfffffaffef1c1214 - std::panicking::try::h44b63116cd2b01fa
  16: 0xfffffaffef1f0d3c - std::rt::lang_start_internal::h3c4b2151dc4654ff
  17:           0x418787 - <unknown>
  18:           0x42a251 - <unknown>
  19:           0x415eb7 - <unknown>
  20:           0x415e18 - <unknown>

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:184", "backtrace-debuginfo.rs:121"]

--- stdout
backtrace-debuginfo.rs:121
backtrace-debuginfo.rs:184

--- stderr
test case 5
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/runtime/backtrace-debuginfo.rs:96:5:
explicit panic
stack backtrace:
   0: 0xfffffaffef018e7f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc081a55a0f1780b5
   1: 0xfffffaffef08e49b - core::fmt::write::h35f0fe8e729713e4
   2: 0xfffffaffef056a18 - std::io::Write::write_fmt::heb110bcb762ba542
   3: 0xfffffaffef018c77 - std::sys_common::backtrace::print::h0c24713efa5b4e4b
   4: 0xfffffaffef020f5a - std::panicking::default_hook::{{closure}}::hf5143a727765c9bd
   5: 0xfffffaffef020c52 - std::panicking::default_hook::hf518dfe583c971c6
   6: 0xfffffaffef021802 - std::panicking::rust_panic_with_hook::h6f0cad0c94a63f1a
   7:           0x418bff - <unknown>
   8:           0x41791d - <unknown>
   9:           0x418ba1 - <unknown>
  10:           0x428d9a - <unknown>
  11:           0x42a1ee - <unknown>
  12:           0x419d9e - <unknown>
  13:           0x417931 - <unknown>
  14:           0x4187b4 - <unknown>
  15: 0xfffffaffef021214 - std::panicking::try::h44b63116cd2b01fa
  16: 0xfffffaffef050d3c - std::rt::lang_start_internal::h3c4b2151dc4654ff
  17:           0x418787 - <unknown>
  18:           0x42a251 - <unknown>
  19:           0x415eb7 - <unknown>
  20:           0x415e18 - <unknown>

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:184", "backtrace-debuginfo.rs:121", "backtrace-debuginfo.rs:104"]

--- stdout
backtrace-debuginfo.rs:104
backtrace-debuginfo.rs:121
backtrace-debuginfo.rs:184

--- stderr
test case 6
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/runtime/backtrace-debuginfo.rs:102:9:
explicit panic
stack backtrace:
   0: 0xfffffaffef0a8e7f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc081a55a0f1780b5
   1: 0xfffffaffef11e49b - core::fmt::write::h35f0fe8e729713e4
   2: 0xfffffaffef0e6a18 - std::io::Write::write_fmt::heb110bcb762ba542
   3: 0xfffffaffef0a8c77 - std::sys_common::backtrace::print::h0c24713efa5b4e4b
   4: 0xfffffaffef0b0f5a - std::panicking::default_hook::{{closure}}::hf5143a727765c9bd
   5: 0xfffffaffef0b0c52 - std::panicking::default_hook::hf518dfe583c971c6
   6: 0xfffffaffef0b1802 - std::panicking::rust_panic_with_hook::h6f0cad0c94a63f1a
   7:           0x418bff - <unknown>
   8:           0x41791d - <unknown>
   9:           0x418ba1 - <unknown>
  10:           0x428ec3 - <unknown>
  11:           0x42a1ee - <unknown>
  12:           0x419d9e - <unknown>
  13:           0x417931 - <unknown>
  14:           0x4187b4 - <unknown>
  15: 0xfffffaffef0b1214 - std::panicking::try::h44b63116cd2b01fa
  16: 0xfffffaffef0e0d3c - std::rt::lang_start_internal::h3c4b2151dc4654ff
  17:           0x418787 - <unknown>
  18:           0x42a251 - <unknown>
  19:           0x415eb7 - <unknown>
  20:           0x415e18 - <unknown>

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:184", "backtrace-debuginfo.rs:121", "backtrace-debuginfo.rs:106", "backtrace-debuginfo-aux.rs:6"]

--- stdout
backtrace-debuginfo-aux.rs:6
backtrace-debuginfo.rs:106
backtrace-debuginfo.rs:121
backtrace-debuginfo.rs:184

--- stderr
test case 7
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/runtime/backtrace-debuginfo.rs:107:9:
explicit panic
stack backtrace:
   0: 0xfffffaffeeca8e7f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc081a55a0f1780b5
   1: 0xfffffaffeed1e49b - core::fmt::write::h35f0fe8e729713e4
   2: 0xfffffaffeece6a18 - std::io::Write::write_fmt::heb110bcb762ba542
   3: 0xfffffaffeeca8c77 - std::sys_common::backtrace::print::h0c24713efa5b4e4b
   4: 0xfffffaffeecb0f5a - std::panicking::default_hook::{{closure}}::hf5143a727765c9bd
   5: 0xfffffaffeecb0c52 - std::panicking::default_hook::hf518dfe583c971c6
   6: 0xfffffaffeecb1802 - std::panicking::rust_panic_with_hook::h6f0cad0c94a63f1a
   7:           0x418bff - <unknown>
   8:           0x41791d - <unknown>
   9:           0x418ba1 - <unknown>
  10:           0x428a4b - <unknown>
  11:           0x4281e3 - <unknown>
  12:           0x428f5d - <unknown>
  13:           0x42a1ee - <unknown>
  14:           0x419d9e - <unknown>
  15:           0x417931 - <unknown>
  16:           0x4187b4 - <unknown>
  17: 0xfffffaffeecb1214 - std::panicking::try::h44b63116cd2b01fa
  18: 0xfffffaffeece0d3c - std::rt::lang_start_internal::h3c4b2151dc4654ff
  19:           0x418787 - <unknown>
  20:           0x42a251 - <unknown>
  21:           0x415eb7 - <unknown>
  22:           0x415e18 - <unknown>

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:184", "backtrace-debuginfo.rs:121", "backtrace-debuginfo.rs:109", "backtrace-debuginfo-aux.rs:13"]

--- stdout
backtrace-debuginfo-aux.rs:13
backtrace-debuginfo.rs:109
backtrace-debuginfo.rs:121
backtrace-debuginfo.rs:184

--- stderr
test case 8
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/runtime/backtrace-debuginfo.rs:110:9:
explicit panic
stack backtrace:
   0: 0xfffffaffeeef8e7f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc081a55a0f1780b5
   1: 0xfffffaffeef6e49b - core::fmt::write::h35f0fe8e729713e4
   2: 0xfffffaffeef36a18 - std::io::Write::write_fmt::heb110bcb762ba542
   3: 0xfffffaffeeef8c77 - std::sys_common::backtrace::print::h0c24713efa5b4e4b
   4: 0xfffffaffeef00f5a - std::panicking::default_hook::{{closure}}::hf5143a727765c9bd
   5: 0xfffffaffeef00c52 - std::panicking::default_hook::hf518dfe583c971c6
   6: 0xfffffaffeef01802 - std::panicking::rust_panic_with_hook::h6f0cad0c94a63f1a
   7:           0x418bff - <unknown>
   8:           0x41791d - <unknown>
   9:           0x418ba1 - <unknown>
  10:           0x428b8b - <unknown>
  11:           0x429018 - <unknown>
  12:           0x42a1ee - <unknown>
  13:           0x419d9e - <unknown>
  14:           0x417931 - <unknown>
  15:           0x4187b4 - <unknown>
  16: 0xfffffaffeef01214 - std::panicking::try::h44b63116cd2b01fa
  17: 0xfffffaffeef30d3c - std::rt::lang_start_internal::h3c4b2151dc4654ff
  18:           0x418787 - <unknown>
  19:           0x42a251 - <unknown>
  20:           0x415eb7 - <unknown>
  21:           0x415e18 - <unknown>

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:184", "backtrace-debuginfo.rs:121", "backtrace-debuginfo.rs:115"]

--- stdout
backtrace-debuginfo.rs:115
backtrace-debuginfo.rs:121
backtrace-debuginfo.rs:184

--- stderr
test case 9
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/runtime/backtrace-debuginfo.rs:102:9:
explicit panic
stack backtrace:
   0: 0xfffffaffef0c8e7f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc081a55a0f1780b5
   1: 0xfffffaffef13e49b - core::fmt::write::h35f0fe8e729713e4
   2: 0xfffffaffef106a18 - std::io::Write::write_fmt::heb110bcb762ba542
   3: 0xfffffaffef0c8c77 - std::sys_common::backtrace::print::h0c24713efa5b4e4b
   4: 0xfffffaffef0d0f5a - std::panicking::default_hook::{{closure}}::hf5143a727765c9bd
   5: 0xfffffaffef0d0c52 - std::panicking::default_hook::hf518dfe583c971c6
   6: 0xfffffaffef0d1802 - std::panicking::rust_panic_with_hook::h6f0cad0c94a63f1a
   7:           0x418bff - <unknown>
   8:           0x41791d - <unknown>
   9:           0x418ba1 - <unknown>
  10:           0x42911a - <unknown>
  11:           0x42a1ee - <unknown>
  12:           0x419d9e - <unknown>
  13:           0x417931 - <unknown>
  14:           0x4187b4 - <unknown>
  15: 0xfffffaffef0d1214 - std::panicking::try::h44b63116cd2b01fa
  16: 0xfffffaffef100d3c - std::rt::lang_start_internal::h3c4b2151dc4654ff
  17:           0x418787 - <unknown>
  18:           0x42a251 - <unknown>
  19:           0x415eb7 - <unknown>
  20:           0x415e18 - <unknown>
------------------------------------------
--- stderr -------------------------------
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/runtime/backtrace-debuginfo.rs:174:9:
found some errors
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------------------------------------


---- [ui] tests/ui/runtime/out-of-stack.rs stdout ----

error: test run failed!
status: exit status: 101
command: cd "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/runtime/out-of-stack" && RUST_TEST_THREADS="40" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/runtime/out-of-stack/a"
--- stdout -------------------------------
testing: silent-thread
------------------------------------------
--- stderr -------------------------------
thread 'main' panicked at /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/runtime/out-of-stack.rs:43:5:
assertion `left == right` failed
  left: Some(11)
 right: Some(6)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------------------------------------


---- [ui] tests/ui/structs-enums/enum-rec/issue-17431-6.rs stdout ----
diff of stderr:

9	LL | enum Foo { X(Mutex<Option<Box<Foo>>>) }
10	   |                           ++++   +
11	
-	error[E0391]: cycle detected when computing when `Foo` needs drop
-	  --> $DIR/issue-17431-6.rs:5:1
-	   |
-	LL | enum Foo { X(Mutex<Option<Foo>>) }
-	   | ^^^^^^^^
-	   |
-	   = note: ...which immediately requires computing when `Foo` needs drop again
-	   = note: cycle used when computing whether `Foo` needs drop
-	   = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
+	error: aborting due to 1 previous error
21	
-	error: aborting due to 2 previous errors
-	
-	Some errors have detailed explanations: E0072, E0391.
-	For more information about an error, try `rustc --explain E0072`.
+	For more information about this error, try `rustc --explain E0072`.
26	


The actual stderr differed from the expected stderr.
Actual stderr saved to /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/structs-enums/enum-rec/issue-17431-6/issue-17431-6.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args structs-enums/enum-rec/issue-17431-6.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2/bin/rustc" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/structs-enums/enum-rec/issue-17431-6.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/.cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/vendor" "--sysroot" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/stage2" "--target=x86_64-unknown-illumos" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/structs-enums/enum-rec/issue-17431-6" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/native/rust-test-helpers" "-L" "/data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/build/x86_64-unknown-illumos/test/ui/structs-enums/enum-rec/issue-17431-6/auxiliary"
stdout: none
--- stderr -------------------------------
error[E0072]: recursive type `Foo` has infinite size
  --> /data/omnios-build/omniosorg/r151050/_extra/rust-1.80.1/rustc-1.80.1-src/tests/ui/structs-enums/enum-rec/issue-17431-6.rs:5:1
   |
LL | enum Foo { X(Mutex<Option<Foo>>) }
   | ^^^^^^^^                  --- recursive without indirection
   |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to break the cycle
   |
LL | enum Foo { X(Mutex<Option<Box<Foo>>>) }
   |                           ++++   +

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0072`.
------------------------------------------



failures:
    [ui] tests/ui/abi/stack-probes.rs#x64
    [ui] tests/ui/associated-consts/issue-93775.rs
    [ui] tests/ui/abi/stack-probes-lto.rs#x64
    [ui] tests/ui/backtrace/dylib-dep.rs
    [ui] tests/ui/backtrace/std-backtrace.rs
    [ui] tests/ui/backtrace/backtrace.rs
    [ui] tests/ui/backtrace/line-tables-only.rs
    [ui] tests/ui/closures/deeply-nested_closures.rs
    [ui] tests/ui/issues/issue-74564-if-expr-stack-overflow.rs
    [ui] tests/ui/linkage-attr/linkage-attr-does-not-panic-llvm-issue-33992.rs
    [ui] tests/ui/panics/issue-47429-short-backtraces.rs#legacy
    [ui] tests/ui/panics/issue-47429-short-backtraces.rs#v0
    [ui] tests/ui/panics/default-backtrace-ice.rs
    [ui] tests/ui/panics/short-ice-remove-middle-frames.rs
    [ui] tests/ui/panics/runtime-switch.rs#v0
    [ui] tests/ui/panics/runtime-switch.rs#legacy
    [ui] tests/ui/panics/short-ice-remove-middle-frames-2.rs
    [ui] tests/ui/parser/survive-peano-lesson-queue.rs
    [ui] tests/ui/proc-macro/load-panic-backtrace.rs
    [ui] tests/ui/runtime/backtrace-debuginfo.rs
    [ui] tests/ui/runtime/out-of-stack.rs
    [ui] tests/ui/structs-enums/enum-rec/issue-17431-6.rs

test result: FAILED. 16777 passed; 22 failed; 204 ignored; 0 measured; 0 filtered out; finished in 476.50s

Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-illumos target=x86_64-unknown-illumos
